version: '3.8'
services:
  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "caja"
      MYSQL_ROOT_PASSWORD: "edcr"
    ports:
      - 3306:3306      
    volumes:
      - db_control:/var/lib/mysql
volumes:
  db_control: